import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SkeletonTheme } from 'react-loading-skeleton';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <SkeletonTheme baseColor="#202020" highlightColor="#444">
      <body className={inter.className}>{children}</body>
      </SkeletonTheme>
    </html>
  )
}
